### ISSUE TITLE
Render usage notes (properties) for Code Systems

### ISSUE THREAD

**Issue by cooperthompson** [HL7/kindling#104]
CodeSystem supports a property element, which can be used to include (for example) usage notes.  However, that information isn't displayed anywhere in the rendered page.

Example:  http://hl7.org/fhir/2022Sep/codesystem-sex-for-clinical-use.html

It would be nice if the property content could be displayed alongside each concept in the rendered view.

**Comment by cooperthompson** [comment]
In [FHIR-39213](https://jira.hl7.org/browse/FHIR-39213), there was some confusion as to why the property definition was listed in the code system definition.  If we get to this issue and make an update such that properties (such as usage notes) are displayed in the HTML rendering, then can we also tweak how the property definitions are displayed?  I don't have any specific suggestions, just the data point that at least one reader didn't understand what properties were or why the definitions were listed in the code system page.

**Comment by grahamegrieve** [comment]
properties are only rendered in the page if they have an extension http://hl7.org/fhir/StructureDefinition/rendered-value that says what the column title for the property should be. Give it a rendered value, and it'll appear

**Comment by cooperthompson** [comment]
One minor point we noticed, but the element is CodeSystem.property.uri, but the column header says URL.  Should the column header be URI instead of URL?

**Comment by grahamegrieve** [comment]
yes. I fixed it for next release
