### ISSUE TITLE
Bindings on "complex" data types should show in resource's terminology list

### ISSUE THREAD

**Issue by ElliotSilver** [HL7/kindling#17]
For example, Dosage.additionalInstruction has an example binding of SNOMED CT Additional Dosage Instructions. The Dosage structure page doesn't have a Terminology section, and this binding for MedicationUsage.dosage is not listed on the MedicationUsage page (see http://build.fhir.org/medicationusage.html#tx). 

This issue is also in 4.0.1 (see https://www.hl7.org/fhir/medicationstatement.html#tx). However, the binding is listed in profiles that depend on MedicationStatement (http://hl7.org/fhir/uv/ips/StructureDefinition-MedicationStatement-uv-ips.html#terminology-bindings).

I don't know if it's the same issue, but parent structure bindings also are not listed for resources (e.g.  ```.language``` elements). If you look at the above profile, it does list the binding on language.

**Comment by lmckenzi** [comment]
We don't want to propagate bindings within complex types up to the referencing structures.  That would do things like put Identifier Type, Address Use, etc. on a whole bunch of resources.  What *should* happen is that there should be a Bindings table on the Dosage type.  However, that's not a tooling thing.  Have created https://jira.hl7.org/browse/FHIR-37472 to fix this (and check to see if there's a similar problem anywhere else).
