### ISSUE TITLE
Prevent case-based collisions

### ISSUE THREAD

**Issue by GinoCanessa** [HL7/kindling#53]
As highlighted in https://jira.hl7.org/browse/FHIR-35770 , there can be collisions in various languages if two components are only differentiated by case (e.g., an element and a value-set).

It would be good if the tooling prevented authors from using the same literal with only case-changes to prevent unexpected issues downstream.

Discussed on FHIR-I WGM call and posting issue here as requested.

**Comment by lmckenzi** [comment]
Not clear why element names aren't prefixed by their resource name - backbone element type names aren't currently required to be globally unique across FHIR (or are they?)  At minimum, need to enforce that ids must be unique independent of case.  This should be true for .name and .title as well.

**Comment by GinoCanessa** [comment]
In the serialized formats names are not prefixed.  So a backbone element named `resourceType` is only distinguishable from the JSON resource discriminator `resourceType` by knowing the relative location in parsing.

That said, the issue open here is for things like `MyElement` being bound to `myElement` - language conventions generally coerce the casing uniformly (e.g., PascalCase) so casing differences are not useful.

**Comment by grahamegrieve** [comment]
This is not an issue in the FHIR specification. Language generators have to figure this out. It's not FHIRs problem if they choose to generate conflicting names
