### ISSUE TITLE
Add forbidden keywords set

### ISSUE THREAD

**Issue by GinoCanessa** [HL7/kindling#54]
Some literals should not be allowed for use as elements/value-sets/etc.  For example, an element named 'resourceType' on the root of a resource would be valid, but cause significant issues with JSON serialization.

I propose adding a file with a set of invalid keywords that can be used by the tooling to prevent issues.  E.g., type literals from different languages, etc.

Thanks!

**Comment by lmckenzi** [comment]
'resourceType' is already covered in the tooling.  We don't intend to prohibit key words from other languages - e.g. 'class', 'type', 'number' are all element names that appear in some resource or data type and also happen to be reserved words in at least one language.  We can't possibly prohibit all such words, particularly as new languages come into play.  It's up to the reference implementations to decide how to best manage these collisions.
